swagger: '2.0'
info:
  description: 'Learn with Grok API'
  version: 1.0.0
  title: OpenAPI Grok
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
host: learn-with-grok.swagger.io
basePath: /
tags:
  - name: translate
    description: All endpoints related to translation
  - name: excerpt
    description: All endpoints related to excerpts
  - name: user
    description: All endpoints related to user
schemes:
  - http
paths:
  /translate:
    post:
      tags:
        - translate
      summary: Translate a sentence
      description: ''
      operationId: translateText
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Translated Text
          required: true
          schema:
            $ref: '#/definitions/TranslatedText'
      responses:
        '405':
          description: Invalid input
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /sentence_tokenize:
    post:
      tags:
        - excerpt
      summary: Tokenize an excerpt into sentences
      description: ''
      operationId: sentence_tokenize
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Excerpt of text
          required: true
          schema:
            $ref: '#/definitions/Excerpt'
      responses:
        '405':
          description: Invalid input
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/signup:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '405':
          description: Invalid input
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  TranslatedText:
    title: Translated Text
    description: Translated text
    type: object
    required:
      - text
    properties:
      text:
        type: string
        example: Hello World!
      source:
        type: string
        example: ES
      target:
        type: string
        example: GB
  Excerpt:
    title: Excerpt of text
    description: Excerpt of text
    type: object
    required:
      - excerpt
    properties:
      excerpt:
        type: string
        example: Hello World! My name is Craig.
      language:
        type: string
        example: GB
  User:
    title: User object
    description: Container Email, Username, password, re-entered password and signup form data
    type: object
  ApiResponse:
    title: A generic response
    description: Generic API response
    type: object
