swagger: '2.0'
info:
  description: 'Learn with Grok API'
  version: 1.0.0
  title: OpenAPI Grok
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
host: learn-with-grok.swagger.io
basePath: /
tags:
  - name: translate
    description: All endpoints related to translation
  - name: excerpt
    description: All endpoints related to excerpts
  - name: user
    description: All endpoints related to user
  - name: story
    description: All endpoints related to story
  - name: library
    description: All endpoints related to the library
  - name: test
    description: All endpoints related to test
schemes:
  - http
paths:
  /translate:
    post:
      tags:
        - translate
      summary: Translate a sentence
      description: ''
      operationId: translateText
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Translated Text
          required: true
          schema:
            $ref: '#/definitions/TranslatedText'
      responses:
        '405':
          description: Invalid input
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /sentence_tokenize:
    post:
      tags:
        - excerpt
      summary: Tokenize an excerpt into sentences
      description: ''
      operationId: sentence_tokenize
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Excerpt of text
          required: true
          schema:
            $ref: '#/definitions/Excerpt'
      responses:
        '405':
          description: Invalid input
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /text_to_speech:
    post:
      tags:
        - excerpt
      summary: Sound out sentence
      description: ''
      operationId: textToSpeech
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Sentence to sound out
          required: true
          schema:
            $ref: '#/definitions/GenericBody'
      responses:
        '405':
          description: Invalid input
        '200':
          description: successful operation
          schema:
            $ref: '#/components/schemas/SynthesizeSpeechResponse'
  /user/signup:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/login:
    post:
      tags:
        - user
      summary: Login user
      description: Log in to grok
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/LoginInfo'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/logout:
    post:
      tags:
        - user
      summary: Log out user
      description: Log out of grok
      operationId: logout
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/fetch:
    post:
      tags:
        - user
      summary: Get the current user
      description: Get the current user
      operationId: fetchUser
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/verifyEmail:
    post:
      tags:
        - user
      summary: Verify Email of current user
      description: Verify Email of current user
      operationId: verifyEmail
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/sendVerifyEmail:
    post:
      tags:
        - user
      summary: Send Verify Email to current user
      description: Send Verify Email to current user
      operationId: sendVerifyEmail
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/sendResetPasswordEmail:
    post:
      tags:
        - user
      summary: Send Reset Password for current user
      description: Send Reset Password for current user
      operationId: sendResetPasswordEmail
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User email to send reset password link
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/resetPassword:
    post:
      tags:
        - user
      summary: Reset Password for current user
      description: Reset Password for current user
      operationId: resetPassword
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: New password for user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/checkResetPasswordToken:
    get:
      tags:
        - user
      summary: Check Reset Password token
      description: Check Reset Password token
      operationId: checkResetPasswordToken
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: token
          type: string
          required: true
          description: Check reset password token
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/update:
    post:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Update user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /user/avatar:
    post:
      tags:
        - user
      summary: Upload avatar
      description: This can only be done by the logged in user.
      operationId: uploadAvatar
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Contains the user's avatar
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /library/fetch:
    post:
      tags:
        - library
      summary: Fetch the library for the current user
      description: Fetch the library for the current user
      operationId: fetchLibrary
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Contains the Library Requesy
          required: true
          schema:
            $ref: '#/definitions/LibraryRequest'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /story/answer:
    post:
      tags:
        - story
      summary: Update user score when a correct answer is selected
      description: This can only be done by the logged in user.
      operationId: answer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Answer to multiple choice question
          required: true
          schema:
            $ref: '#/definitions/Answer'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /story/attempt/new:
    post:
      tags:
        - story
      summary: Create a new attempt to retry a story
      description: Create a new attempt to retry a story
      operationId: newAttempt
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Short story translation id to create a new attempt
          required: true
          schema:
            $ref: '#/definitions/GenericBody'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /story/attempt/fetch:
    post:
      tags:
        - story
      summary: Fetch all attempts by user for a story
      description: Fetch all attempts by user for a story
      operationId: fetchAttempts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Short story translation id to create a new attempt
          required: true
          schema:
            $ref: '#/definitions/GenericBody'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
  /test/checkResetPasswordToken:
    get:
      tags:
        - test
      summary: Check token
      description: Check token
      operationId: checkToken
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: token
          type: string
          required: true
          description: Check reset password token
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  TranslatedText:
    title: Translated Text
    description: Translated text
    type: object
    required:
      - text
    properties:
      text:
        type: string
        example: Hello World!
      source:
        type: string
        example: ES
      target:
        type: string
        example: GB
  Excerpt:
    title: Excerpt of text
    description: Excerpt of text
    type: object
    required:
      - excerpt
    properties:
      excerpt:
        type: string
        example: Hello World! My name is Craig.
      language:
        type: string
        example: GB
  User:
    title: User object
    description: Contains Email, Username, password, re-entered password and signup form data
    type: object
  LibraryRequest:
    title: Library Request
    description: Contains the grade or story selected
    type: object
  LoginInfo:
    title: Login Info
    description: Username and password
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        example: user1
      password:
        type: string
        example: hunter42
  Answer:
    title: Answer to multiple choice question
    description: Answer to multiple choice question
    type: object
  SynthesizeSpeechResponse:
      description: The message returned to the client by the `SynthesizeSpeech` method.
      properties:
        audioContent:
          description: |-
            The audio data bytes encoded as specified in the request, including the
            header for encodings that are wrapped in containers (e.g. MP3, OGG_OPUS).
            For LINEAR16 audio, we include the WAV header. Note: as
            with all bytes fields, protobuffers use a pure binary representation,
            whereas JSON representations use base64.
          format: byte
          type: string
      type: object
  GenericBody:
    title: A generic body
    description: Generic API body
    type: object
  ApiResponse:
    title: A generic response
    description: Generic API response
    type: object
