# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TranslatedText(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text=None, source=None, target=None):  # noqa: E501
        """TranslatedText - a model defined in OpenAPI

        :param text: The text of this TranslatedText.  # noqa: E501
        :type text: str
        :param source: The source of this TranslatedText.  # noqa: E501
        :type source: str
        :param target: The target of this TranslatedText.  # noqa: E501
        :type target: str
        """
        self.openapi_types = {
            'text': str,
            'source': str,
            'target': str
        }

        self.attribute_map = {
            'text': 'text',
            'source': 'source',
            'target': 'target'
        }

        self._text = text
        self._source = source
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> 'TranslatedText':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TranslatedText of this TranslatedText.  # noqa: E501
        :rtype: TranslatedText
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self):
        """Gets the text of this TranslatedText.


        :return: The text of this TranslatedText.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this TranslatedText.


        :param text: The text of this TranslatedText.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def source(self):
        """Gets the source of this TranslatedText.


        :return: The source of this TranslatedText.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this TranslatedText.


        :param source: The source of this TranslatedText.
        :type source: str
        """

        self._source = source

    @property
    def target(self):
        """Gets the target of this TranslatedText.


        :return: The target of this TranslatedText.
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this TranslatedText.


        :param target: The target of this TranslatedText.
        :type target: str
        """

        self._target = target
