"""empty message

Revision ID: 0dd1e00aedd6
Revises: 851a58bc0456
Create Date: 2020-05-18 18:41:25.652252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd1e00aedd6'
down_revision = '851a58bc0456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_story_translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_story_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['short_story_id'], ['short_story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_story_translation')
    # ### end Alembic commands ###
