"""empty message

Revision ID: 1807c6a65e7c
Revises: 85ae944a622c
Create Date: 2020-05-23 16:53:59.501305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1807c6a65e7c'
down_revision = '85ae944a622c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_story_attempt', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_story_attempt', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_story_attempt', type_='foreignkey')
    op.drop_column('user_story_attempt', 'user_id')
    # ### end Alembic commands ###
