"""empty message

Revision ID: 21487010df1f
Revises: 4328471e9119
Create Date: 2020-05-21 19:25:22.618886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21487010df1f'
down_revision = '4328471e9119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiple_choice_answer_translation', sa.Column('multiple_choice_question_translation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'multiple_choice_answer_translation', 'multiple_choice_question_translation', ['multiple_choice_question_translation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multiple_choice_answer_translation', type_='foreignkey')
    op.drop_column('multiple_choice_answer_translation', 'multiple_choice_question_translation_id')
    # ### end Alembic commands ###
