"""empty message

Revision ID: 2334ca815381
Revises: 944b0f174574
Create Date: 2020-05-20 22:48:23.307100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2334ca815381'
down_revision = '944b0f174574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_history', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('language_synonym', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('language_synonym', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('language_synonym', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('multiple_choice_answer', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('multiple_choice_question', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('school_level', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('school_level', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('school_level', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('school_level_translation', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('school_level_translation', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('school_level_translation', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('short_story', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('short_story_content', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('short_story_translation', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user_role', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'deleted_at')
    op.drop_column('user', 'deleted_at')
    op.drop_column('short_story_translation', 'deleted_at')
    op.drop_column('short_story_content', 'deleted_at')
    op.drop_column('short_story', 'deleted_at')
    op.drop_column('school_level_translation', 'updated_at')
    op.drop_column('school_level_translation', 'deleted_at')
    op.drop_column('school_level_translation', 'created_at')
    op.drop_column('school_level', 'updated_at')
    op.drop_column('school_level', 'deleted_at')
    op.drop_column('school_level', 'created_at')
    op.drop_column('multiple_choice_question', 'deleted_at')
    op.drop_column('multiple_choice_answer', 'deleted_at')
    op.drop_column('language_synonym', 'updated_at')
    op.drop_column('language_synonym', 'deleted_at')
    op.drop_column('language_synonym', 'created_at')
    op.drop_column('language_history', 'deleted_at')
    # ### end Alembic commands ###
