"""empty message

Revision ID: 24ec47e3c205
Revises: d9af01fb46c7
Create Date: 2020-05-17 14:16:56.838706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ec47e3c205'
down_revision = 'd9af01fb46c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('language_history', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_history', 'updated_at')
    op.drop_column('language_history', 'created_at')
    # ### end Alembic commands ###
