"""empty message

Revision ID: 26a7a9cc9676
Revises: 0dd1e00aedd6
Create Date: 2020-05-18 19:19:14.982667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a7a9cc9676'
down_revision = '0dd1e00aedd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_story', sa.Column('illustration_url', sa.String(length=128), nullable=True))
    op.drop_column('short_story_content', 'illustration_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_story_content', sa.Column('illustration_url', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('short_story', 'illustration_url')
    # ### end Alembic commands ###
