"""empty message

Revision ID: 2cffa8e5c42b
Revises: 8ce68d4685f3
Create Date: 2020-05-11 20:57:11.143329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cffa8e5c42b'
down_revision = '8ce68d4685f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_email_lower_idx', 'user', ['email_lower'], unique=False)
    op.create_index('user_username_idx', 'user', ['username'], unique=False)
    op.create_unique_constraint(None, 'user', ['email_lower'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index('user_username_idx', table_name='user')
    op.drop_index('user_email_lower_idx', table_name='user')
    # ### end Alembic commands ###
