"""empty message

Revision ID: 39bcd8ac4ea3
Revises: 1807c6a65e7c
Create Date: 2020-05-23 21:38:50.008741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bcd8ac4ea3'
down_revision = '1807c6a65e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_story_attempt', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_story_attempt', 'is_complete')
    # ### end Alembic commands ###
