"""empty message

Revision ID: 4328471e9119
Revises: 2334ca815381
Create Date: 2020-05-21 19:11:50.750634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4328471e9119'
down_revision = '2334ca815381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiple_choice_question_translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_story_id', sa.Integer(), nullable=True),
    sa.Column('multiple_choice_question_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['multiple_choice_question_id'], ['multiple_choice_question.id'], ),
    sa.ForeignKeyConstraint(['short_story_id'], ['short_story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiple_choice_answer_translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('multiple_choice_question_id', sa.Integer(), nullable=True),
    sa.Column('multiple_choice_answer_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['multiple_choice_answer_id'], ['multiple_choice_answer.id'], ),
    sa.ForeignKeyConstraint(['multiple_choice_question_id'], ['multiple_choice_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiple_choice_answer_translation')
    op.drop_table('multiple_choice_question_translation')
    # ### end Alembic commands ###
