"""empty message

Revision ID: 520f263a56f6
Revises: 21487010df1f
Create Date: 2020-05-23 11:39:49.198246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520f263a56f6'
down_revision = '21487010df1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_story', sa.Column('story_by', sa.String(length=256), nullable=True))
    op.add_column('short_story', sa.Column('story_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'short_story', 'user', ['story_by_user_id'], ['id'])
    op.add_column('short_story_translation', sa.Column('translated_by', sa.String(length=256), nullable=True))
    op.add_column('short_story_translation', sa.Column('translated_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'short_story_translation', 'user', ['translated_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_story_translation', type_='foreignkey')
    op.drop_column('short_story_translation', 'translated_by_user_id')
    op.drop_column('short_story_translation', 'translated_by')
    op.drop_constraint(None, 'short_story', type_='foreignkey')
    op.drop_column('short_story', 'story_by_user_id')
    op.drop_column('short_story', 'story_by')
    # ### end Alembic commands ###
