"""empty message

Revision ID: 53e1c2fe7c38
Revises: a6c0a4be6099
Create Date: 2020-05-16 21:46:09.753229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e1c2fe7c38'
down_revision = 'a6c0a4be6099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiple_choice_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_story_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['short_story_id'], ['short_story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiple_choice_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('multiple_choice_question_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['multiple_choice_question_id'], ['multiple_choice_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('short_story', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('short_story', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('short_story_content', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('short_story_content', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_story_content', 'updated_at')
    op.drop_column('short_story_content', 'created_at')
    op.drop_column('short_story', 'updated_at')
    op.drop_column('short_story', 'created_at')
    op.drop_table('multiple_choice_answer')
    op.drop_table('multiple_choice_question')
    # ### end Alembic commands ###
