"""empty message

Revision ID: 559584321209
Revises: 
Create Date: 2020-05-11 20:10:39.620114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559584321209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_synonym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('long_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_lower', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('native_language', sa.String(length=10), nullable=True),
    sa.Column('language_i_want_to_learn', sa.String(length=10), nullable=True),
    sa.Column('has_studied_foreign_language', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('yearsOfStudy', sa.Integer(), nullable=True),
    sa.Column('proficiencyLevel', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_history')
    op.drop_table('user')
    op.drop_table('school_level')
    op.drop_table('language_synonym')
    # ### end Alembic commands ###
