"""empty message

Revision ID: 5aeabc8c5fdc
Revises: c6aab386d246
Create Date: 2020-05-14 20:20:21.763121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aeabc8c5fdc'
down_revision = 'c6aab386d246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(length=128), nullable=True))
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
