"""empty message

Revision ID: 68726ace3ab4
Revises: 6d5fac748438
Create Date: 2020-06-25 19:35:58.482511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68726ace3ab4'
down_revision = '6d5fac748438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verify_email_link_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verify_email_link_sent')
    # ### end Alembic commands ###
