"""empty message

Revision ID: 85ae944a622c
Revises: 520f263a56f6
Create Date: 2020-05-23 16:28:28.020316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ae944a622c'
down_revision = '520f263a56f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_story_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_story_id', sa.Integer(), nullable=True),
    sa.Column('short_story_translation_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['short_story_id'], ['short_story.id'], ),
    sa.ForeignKeyConstraint(['short_story_translation_id'], ['short_story_translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_story_attempt')
    # ### end Alembic commands ###
