"""empty message

Revision ID: 8ce68d4685f3
Revises: 854a80a1d869
Create Date: 2020-05-11 20:44:25.182322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce68d4685f3'
down_revision = '854a80a1d869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_history', sa.Column('proficiency_level', sa.String(length=30), nullable=True))
    op.add_column('language_history', sa.Column('years_of_study', sa.Integer(), nullable=True))
    op.drop_column('language_history', 'proficiencyLevel')
    op.drop_column('language_history', 'yearsOfStudy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_history', sa.Column('yearsOfStudy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('language_history', sa.Column('proficiencyLevel', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('language_history', 'years_of_study')
    op.drop_column('language_history', 'proficiency_level')
    # ### end Alembic commands ###
