"""empty message

Revision ID: 944b0f174574
Revises: 26a7a9cc9676
Create Date: 2020-05-18 19:51:10.235190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944b0f174574'
down_revision = '26a7a9cc9676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_level_translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_level_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_level_id'], ['school_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_level_translation')
    # ### end Alembic commands ###
