"""empty message

Revision ID: a6c0a4be6099
Revises: f1d38aa6e303
Create Date: 2020-05-16 00:21:59.773245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c0a4be6099'
down_revision = 'f1d38aa6e303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_story', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_story', 'published_at')
    # ### end Alembic commands ###
