"""empty message

Revision ID: d9af01fb46c7
Revises: 53e1c2fe7c38
Create Date: 2020-05-16 21:51:37.065917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9af01fb46c7'
down_revision = '53e1c2fe7c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiple_choice_answer', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('multiple_choice_answer', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.add_column('multiple_choice_answer', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_column('multiple_choice_answer', 'question')
    op.add_column('multiple_choice_question', sa.Column('sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multiple_choice_question', 'sequence')
    op.add_column('multiple_choice_answer', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('multiple_choice_answer', 'order')
    op.drop_column('multiple_choice_answer', 'is_correct')
    op.drop_column('multiple_choice_answer', 'answer')
    # ### end Alembic commands ###
