"""empty message

Revision ID: f1d38aa6e303
Revises: 5aeabc8c5fdc
Create Date: 2020-05-14 21:06:25.122231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d38aa6e303'
down_revision = '5aeabc8c5fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_level_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['school_level_id'], ['school_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_story_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_story_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('illustration_url', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['short_story_id'], ['short_story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('school_level', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('school_level', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('school_level', sa.Column('sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_level', 'sequence')
    op.drop_column('school_level', 'name')
    op.drop_column('school_level', 'language')
    op.drop_table('short_story_content')
    op.drop_table('short_story')
    # ### end Alembic commands ###
